### ISSUE TITLE
NineSlice doesn't re-load image (And it should)

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#320] opened 2024-12-10 08:05 UTC
When I edit an image outside of Gum, and save it, Gum doesn't re-load the image.  Even if I manually select the image again from the Source File ... picker.  This is extra work for the user.  

Gum **SHOULD** automatically re-load any changes to the PNG files it is using in the SOURCE, at a minimum when the user clicks off and back onto the control, Ideally it should "watch" the source file for changes and then reload upon a change.

**Other observations:**
- It seems to "Cache" the image by filename.
- If I change the filename, and then chose the image, it loads the updated image finally.

**Steps to reproduce:**
1. Notice in the video, I have a NineSlice, and a PNG open in MSPaint.  
2. Edit the PNG and SAVE It
3. Notice that Nothing updates in Gum, even if you click off the NineSlice, change the Tab to and from Texture Coordinates
4. Now try to re-open the file by selecting the ... and finding the file, notice nothing updates in Gum
5. Now try to select a DIFFERENT file, notice it updates
6. Now try to re-select the original file, notice it doesn't have the updated changes
7. Now try to re-name the original file by adding a "2" to the end, select that file, notice Gum now finally reflects the updated PNG file

https://github.com/user-attachments/assets/6f6cbf8e-8330-4cda-bf26-b36a0f7e5b03

**Comment by vchelaru** [comment] 2024-12-23 14:38
I could not reproduce this error.
![23_07 36 40](https://github.com/user-attachments/assets/2624b65d-f1c6-4214-ae77-17818e453772)
Since we have had file watch errors in the past, there's a File Watch tab which you can click on to get some diagnostic info about what is happening.

Could you try again and keep an eye on that tab to see if it tells us why it isn't working?

![image](https://github.com/user-attachments/assets/84087a88-a0d7-41bc-a3c6-713376e59ab7)

Maybe that will give us some hints as to why it's not working. If not we may have to debug locally on your machine to see what's up.

**Comment by kaltinril** [comment] 2024-12-24 06:51
nope doesn't work

https://github.com/user-attachments/assets/6c7e19c5-ee15-413d-be59-6a053d31ea27

**Comment by kaltinril** [comment] 2024-12-24 06:53
With file watch, going to try it again with a project OUTSIDE the OneDrive folder


https://github.com/user-attachments/assets/c57421b3-ee0e-44bd-b85d-bdbf3e194377

**Comment by kaltinril** [comment] 2024-12-24 06:59
nope, even outside onedrive doesn't work


https://github.com/user-attachments/assets/805be183-aa5a-443d-a526-2204d3451baf

**Comment by kaltinril** [comment] 2024-12-24 07:02
I did notice that the watch location didn't update until I used Load Project, it was stuck on the previous project.

I'll open a bug for that file watch not updating on New Project, but, that's not my issue because I did a load project to force it to show the correct file watch path and it still didn't work

https://github.com/user-attachments/assets/9bc8e862-f1d2-4de3-8178-51dcec434195

**Comment by kaltinril** [comment] 2024-12-24 08:08
It doesn't appear file watching is working at all for me for anything.

I put a breakpoint on this step and modified a components *.gucx file to remove a TextInstance from the XML and nothing changed

![image](https://github.com/user-attachments/assets/583e1b97-4a68-4ebc-8f25-84ebceae1efb)

**Comment by vchelaru** [comment] 2024-12-24 13:50
I merged the PR you made earlier and this included a few small fixes to file watch which may have helped with the issues here. That said, if you are able to reproduce it, it may require us both getting on a call and debugging on your machine since I'm currently unable to reproduce the problem.

**Comment by kaltinril** [comment] 2024-12-24 23:15
> I merged the PR you made earlier and this included a few small fixes to file watch which may have helped with the issues here. That said, if you are able to reproduce it, it may require us both getting on a call and debugging on your machine since I'm currently unable to reproduce the problem.


When you're available let me know and lets test on my machine

![image](https://github.com/user-attachments/assets/ee02ee8a-db5d-46d0-aa6b-bdd455442100)

**Comment by kaltinril** [comment] 2024-12-25 01:14
Tested with latest fix you pushed, it is now working.  You may close this at your hearts content.

https://github.com/user-attachments/assets/154d3b3e-ebf9-4dc5-bc30-fc501cafcdaa

**Closed** 2024-12-25 03:02 UTC
Labels: bug
