### ISSUE TITLE
Gum should persist animation chain changes

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/Gum#244] opened 2024-11-05 21:46 UTC
Gum has buggy behavior after setting an animation chain on a sprite object. It will often revert to the previous chain and may not correctly resize the sprite.

**Scenario 1:**

1. Create a sprite
2. Set the sprite source to be an achx file
3. Change the animation chain
4. Drag the sprite in the Gum editor window
5. Observe that the animation chain reverts to the previous setting upon dragging

**Scenario 2:**

1. Create a sprite
2. Set the sprite source to be an achx file
3. Make sure the sprite is set to be 100% of the source file in both dimensions
4. Set the animation chain to a 32x32 chain for example
5. Now change the animation chain to a 32x64 chain for example
6. Observe that the sprite is not properly scaled, original aspect ratio is maintained and sprite becomes distorted

**Expected**: Gum properly shows the selected animation chain at the correct dimensions
**Actual**: Gum behavior with sprite previews when the sprite source is an animation chain is erratic

**Comment by vchelaru** [comment] 2024-11-07 13:36
Scenario 2 has been fixed with commit 7d3f2992ad405e6844aa4b4ff7e339ea9bf0779c

I could not reproduce scenario 1, but perhaps the fix also addresses that? We may need to get on a call for scenario 1 if not.

**Comment by vchelaru** [comment] 2024-11-08 12:40
I believe this may be fixed, but I will need a project or repro steps, or perhaps to get on a call together to figure out issue #1. I'm going to close this issue for now but it can be re-opened or a new issue can be created if the commit above does not fix the issues.

**Closed by vchelaru** 2024-11-08 12:40 UTC
Labels: bug
