### ISSUE TITLE
Modal root can't be used for tooltips

### ISSUE THREAD

**Issue by legendaryfishtrap** [vchelaru/Gum#237] opened 2024-10-30 21:34 UTC
Trying to use the modal root to create a tooltip on hover. But when the tooltip is spawned it triggers the RollOff which then closes it again. Attached is a video showcasing the issue.

I made an example of the issue in the MonoGame samples in a fork of the repo here: https://github.com/legendaryfishtrap/Gum/tree/WIP_Tooltip

https://github.com/user-attachments/assets/88dc79c4-79e1-4ca6-b30a-905bfa3157ef

**Comment by vchelaru** [comment] 2024-10-31 13:32
There are two problems here:

1. There was a bug which caused RollOn to be raised continually. This was actually not affecting your app, but it would have so I've fixed it with this commit: https://github.com/vchelaru/Gum/commit/522646d7258e8498c2f9e3441f4e2234f73cfbf0
2. This is actually behaving as designed. The reason is that you are showing a tooltip as a modal. When the tooltip appears as a modal, that means no other control can receive input. Therefore, the button that you were rolling over previously is no longer getting input, so it loses the roll state, raising its Roll Off which hides the tooltip. Then the next frame, the modal tooltip is gone so the cursor once-again receives input events and so it registers a Roll On. The fix for this is to show the tooltip on the regular (non-modal) PopupRoot. If you do this, you will see your tooltip accumulating every frame unless you pull the latest (see point # 1)

Once I made the fix all worked fine so I'm closing this issue out. As always please let me know if you have any more issues.

**Closed by vchelaru** 2024-10-31 13:32 UTC
