### ISSUE TITLE
UI: (Low) Base Type error on Behavior Required Instance (Unable to select last item in list)

### ISSUE THREAD

**Issue by kaltinril** [vchelaru/Gum#425] opened 2024-12-28 01:18 UTC
I don't know the purpose of the Base Type on a Instance that's added to a Behavior.

But, I get this incorrect error message when I try to select the LAST ITEM in the list.

**Warning/Error:** "The assignment would create a circular reference, which is not allowed"

**Steps to reproduce:**
1. Create a component named "aComp" so it's first in the list
2. Create a behavior
3. Drag the "aComp" Component to the Behavior
4. Create another component named "zComp" so it's last in the list 
5. Click on the Behavior Instance of the component
6. From the Base Type drop down select zComp
7. Notice you get the warning/error.
8. Create a 3rd component named "zzComp" so it sorts after "zComp".
9. Click back on the Behavior Instance of the component
10. From the Base Type drop down select zComp, notice this time, no error.

![image](https://github.com/user-attachments/assets/a5f587cc-b662-4256-9661-ca13fbbf0039)

(Ignore the other error, I accidently kept clicking on the folder)
https://github.com/user-attachments/assets/510e13cc-d18f-4314-b7eb-140ed19aa878

**Comment by kaltinril** [comment] 2024-12-28 04:58
Seems the issue here is that, when you select a Component defintion, it's setting the SelectedState.Self.SelectedStateSave.

Then when you select a Base Type to change, the SelectedStateSave is being passed down as the "instanceConatainer" and it shouldn't be.

See `line 72` of `SetVariableLogic.cs` in method `PropertyValueChanged`.

I don't know where SelectedState.Self.SelectedStateSave is being set, because the code is just too vast.

![image](https://github.com/user-attachments/assets/01aaffae-3335-4a82-a9ac-083c5b4fcf6a)

**Comment by vchelaru** [comment] 2024-12-29 14:12
I could not reproduce this, but I've made some fixes since this bug was listed. I'm going to close it, but if you do get a chance to try it out please let me know if it still happens for you.

**Closed** 2024-12-29 14:15 UTC

**Comment by kaltinril** [comment] 2024-12-29 23:12
Yep, it's fixed now that you did that little fix you did just moments ago in commit fd7c215bc0a738c0d10d74c611efd21c85c7f64e
